categories:
  recaptcha: ~
  sf-register:
    label: 'Frontend user registration'

settings:
  evoweb.recaptcha.publicKey:
    default: ''
    type: string
    category: recaptcha
  evoweb.recaptcha.privateKey:
    default: ''
    type: string
    category: recaptcha
  evoweb.recaptcha.apiServer:
    default: ''
    type: string
    category: recaptcha
  evoweb.recaptcha.verifyServer:
    default: ''
    type: string
    category: recaptcha
  evoweb.recaptcha.lang:
    default: ''
    type: string
    category: recaptcha
  evoweb.recaptcha.theme:
    default: ''
    type: string
    enum:
      light: 'light'
      dark: 'dark'
    category: recaptcha
  evoweb.recaptcha.robotMode:
    default: 0
    type: bool
    category: recaptcha
  evoweb.recaptcha.enforceCaptcha:
    default: 0
    type: bool
    category: recaptcha
  evoweb.sf-register.captchaId:
    default: ''
    type: string
    category: sf-register
