services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\Recaptcha\:
    resource: '../Classes/*'

  Evoweb\Recaptcha\Services\CaptchaService:
    public: true

  Evoweb\Recaptcha\Adapter\SfRegisterAdapter:
    public: true
